name: Setup Node
description: Setup Node.js version from .nvmrc

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        cache: npm
        node-version-file: '.nvmrc'
