name: Lighthouse CI
description: Check Lighthouse scores
inputs:
  LHCI_GITHUB_APP_TOKEN:
    description: "Token from Lighthouse CI GitHub App"
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-node
    - run: ls -la
      shell: bash
    - run: |
        npm install -g @lhci/cli
        lhci autorun
      shell: bash
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ inputs.LHCI_GITHUB_APP_TOKEN }}
